[package]
name = "teste"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ncollide2d = "0.22" # For 2D collision detection.
ecs = {path="./ecs"}

[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
version = "0.34"
default-features = false
features = ["ttf","image","gfx","mixer","static-link","use-vcpkg", "unsafe_textures"]

[package.metadata.vcpkg]
dependencies = ["sdl2", "sdl2-image[libjpeg-turbo,tiff,libwebp]", "sdl2-ttf", "sdl2-gfx", "sdl2-mixer"]
git = "https://github.com/microsoft/vcpkg"
rev = "a0518036077baa4"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }