[package]
name = "voxelviewer"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
cgmath = "0.18"
env_logger = "0.9"
pollster = "0.2"
image = "0.23"
log = "0.4"
tobj = "3.0"
wgpu = "0.12"
winit = "0.26"
world = {path="../world"}